# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a2336bae67833ed83c69b3876524b7113dee37452650e51c4be18f3b75ccb13f33589b9f008b07724856802489fb4d62b3565bab6fc49e80d9496db895a108a

test:
  secret_key_base: 64f0b1bef2872bb8c43fa198f9ee39073210522ad06943ef3b85bad8ad77fa56d1a1f77402b8cd324e356892f6ca17a8c5c4cf5aa58a42a51641410b6bda6206

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
